[DANIP_DHIS2]
[OPENAI]

OPENAI_API_KEY= "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"
MODEL = "gpt-5"

[DANIP_DHIS2]

BASE_URL = "https://dhis2.nutritionintl.org"

CLIENT_ID = "nexus-danip-local"

CLIENT_SECRET = "54741bce7-c2b4-b25d-b2da-72534700022"

REDIRECT_URI = "https://mdl-ni-ai.streamlit.app/"

STATE_SECRET = "WMkHmxgJv2TfphYexj6xPd-dC54zzqtdhNLvjnhe8MeKK6OhXkeXkUuqlOB0JFydqIRndPDu5jjxwddAlm73sA"

AUTHORIZE_URL = "https://dhis2.nutritionintl.org/uaa/oauth/authorize"

TOKEN_URL = "https://dhis2.nutritionintl.org/uaa/oauth/token"

ME_URL = "https://dhis2.nutritionintl.org/api/me"

CLIENT_AUTH_METHOD = "post"

