[DANIP_DHIS2]

CLIENT_ID = "YOUR_CLIENT_ID"
CLIENT_SECRET = "YOUR_CLIENT_SECRET"

REDIRECT_URI = "https://mdl-ni-ai.streamlit.app/"

STATE_SECRET = "YOUR_RANDOM_LONG_SECRET"

AUTHORIZE_URL = "https://dhis2.nutritionintl.org/uaa/oauth/authorize"

TOKEN_URL = "https://dhis2.nutritionintl.org/uaa/oauth/token"

ME_URL = "https://dhis2.nutritionintl.org/api/me"

CLIENT_AUTH_METHOD = "post"

[OPENAI]

OPENAI_API_KEY= "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"
MODEL = "gpt-5"
