[DANIP_DHIS2]
[OPENAI]

OPENAI_API_KEY= "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"
MODEL = "gpt-5"

[DANIP_DHIS2]

BASE_URL = "https://dhis2.nutritionintl.org"

CLIENT_ID = "nexus-danip-local"

CLIENT_SECRET = "54741bce7-c2b4-b25d-b2da-72534700022"

REDIRECT_URI = "https://mdl-ni-ai.streamlit.app/"

STATE_SECRET = "WMkHmxgJv2TfphYexj6xPd-dC54zzqtdhNLvjnhe8MeKK6OhXkeXkUuqlOB0JFydqIRndPDu5jjxwddAlm73sA"

AUTHORIZE_URL = "https://dhis2.nutritionintl.org/uaa/oauth/authorize"

TOKEN_URL = "https://dhis2.nutritionintl.org/uaa/oauth/token"

ME_URL = "https://dhis2.nutritionintl.org/api/me"

CLIENT_AUTH_METHOD = "basic"

